export const ArtworkData = [
  {
    name: "Earth 6",
    type: "photos",
    src: "gallery/earf.png",
    tags: ["3d blender sci-fi planets"],
    desc: "One of my first procedural planet renders. I was going for an earth-like planet with it's own moon.",
    gridSize: "",
  },
  {
    name: "Selfie",
    type: "photos",
    src: "gallery/selfie.png",
    desc: "I was learning to rig when I did this one, added some realistic texture with the hair particle system.",
    gridSize: "tall wide",
  },

  {
    name: "The Last Voyage",
    type: "photos",
    src: "gallery/voyage.png",
    tags: ["3d blender concept-art landscapes"],
    desc: "An attempt at creating a procedural scene. The ship and dock were added to .",
    gridSize: "wide",
  },
  {
    name: "Stairway",
    type: "videos",
    src: "gallery/stairway.mp4",
    desc: "Inspired by the intro of Marvel's \"What If...\" series, I was trying to achieve a procedural shading based on the camera's position.",
    gridSize: "tall",
  },
  {
    name: "The Starsnatcher",
    type: "photos",
    src: "gallery/starsnatcher.png",
    tags: ["3d blender sci-fi planets"],
    desc: "A different approach to the same procedure as the Firestorm nebula.",
    gridSize: "tall",
  },
  {
    name: "The Marble",
    type: "photos",
    src: "gallery/pluto.png",
    tags: ["3d blender sci-fi planets"],
    desc: "The inspiration for this planet was Pluto, using it's nice colors and textures as reference.",
    gridSize: "",
  },
  {
    name: "Philharmony",
    type: "photos",
    src: "gallery/philharmony.png",
    tags: ["3d blender abstract graphic-design"],
    desc: "Philrhamony is a two-track project, they needed a cover that would match the mood of the songs.",
    gridSize: "",
  },
  {
    name: "Treeman",
    type: "photos",
    src: "gallery/treeman.png",
    desc: "A 3D sculpture of an old drawing of mine.",
    gridSize: "tall",
  },
  {
    name: "Firestorm Nebula",
    type: "photos",
    src: "gallery/firestorm.png",
    tags: ["3d blender sci-fi planets"],
    desc: "My first try at procedurally creating a nebula.",
    gridSize: "",
  },
  {
    name: "Getaway House",
    type: "photos",
    src: "gallery/river.jpg",
    desc: "The terrain and sky are procedurally generated. The painterly look was achieved with Blender's optiX denoiser.",
    gridSize: "wide",
  },
  {
    name: "Maschine MK3",
    type: "photos",
    src: "gallery/maschine.png",
    desc: "A 3D model of my Maschine MK3. Decided to put it in a little scene.",
    gridSize: "",
  },
  {
    name: "Press Play",
    type: "photos",
    src: "gallery/idjo.jpg",
    desc: "My first try to sculpt in Blender. I think it turned out great.",
    gridSize: "",
  },

  {
    name: "The Hidden Planet",
    type: "photos",
    src: "gallery/secret-planet.png",
    desc: "Blender's fluid simulations were used for the nebula, the planet is procedurally shaded.",
    gridSize: "",
  },
  {
    name: "Microcubes",
    type: "photos",
    src: "gallery/cubez.png",
    desc: "Inspired by the intro of Marvel's \"What If...\" series, I was trying to achieve a procedural shading based on the camera's position.",
    gridSize: "",
  },
  {
    name: "Monkey See",
    type: "videos",
    src: "gallery/monke-see.mp4",
    desc: "Inspired by the intro of Marvel's \"What If...\" series, I was trying to achieve a procedural shading based on the camera's position.",
    gridSize: "wide",
  },
  {
    name: "Chija Si",
    type: "photos",
    src: "gallery/chijasi.png",
    desc: "Winning design for the CD and vinyl cover of LD Pistolero ft. DJ Goce - Chija si",
    gridSize: "",
  },
  {
    name: "Strange Galaxies",
    type: "videos",
    src: "gallery/strange-galaxies.mp4",
    desc: "One of my first tries at A.I. animation and sound design.",
    gridSize: "",
  },
  {
    name: "Ladybugz",
    type: "videos",
    src: "gallery/ladybug.mp4",
    desc: "One of my first tries at A.I. animation and sound design.",
    gridSize: "tall",
  },
];
