export const ArtworkData = [
  {
    name: "Earth 6",
    type: ["images"],
    src: "https://i.imgur.com/OzrD9LB.png",
    tags: ["3d blender sci-fi planets"],
    desc: `A planet made in Blender using a sphere and the shader editor. I was going for an earth-like planet, so the terrain is mainly divided into land and water, each having it's own variations in height/depth. On top of that, there is a layer of procedural clouds which are lit by the sun.
    The direction of the light controls two other aspects as well; firstly, the thin blue layer, which indicates the atmosphere, is only visible where it's hit by the light; whereas in the areas where the light doesn't hit the object, as indication for populated cities a glow is revealed, based on a combination of noise textures.`,
    gridSize: "",
  },
  {
    name: "Selfie",
    type: ["images"],
    src: "https://i.imgur.com/BW0DZAi.png",
    desc: `Played around with rigging in Blender. I was going for a miniature plush toy look. The final render is a bit different from the original sketches I'd done. Originally the eyes were planned as paper cutouts, but I instead opted for buttons with phosphorescent threads.
    For the environment, I used an HDRI of a cityscape in the night, then I blasted the character with a bunch of lights, going for an over-the-top style.`,
    gridSize: "tall wide",
  },
  {
    name: "Topaz",
    type: ["youtube", "videos", "audio"],
    src: "//www.youtube.com/embed/dO-GHJkrh5A",
    desc: 'Track 6 from "Neizbruseni Kamenja" EP',
    gridSize: "",
  },
  {
    name: "The Last Voyage",
    type: ["images"],
    src: "https://i.imgur.com/kOPjpp6.png",
    tags: ["3d blender concept-art landscapes"],
    desc: "An attempt at creating a procedural scene. The ship and dock were added to .",
    gridSize: "wide",
  },

  {
    name: "Stairway",
    type: ["videos", "audio"],
    src: "https://i.imgur.com/T1Eploe.mp4",
    poster: "https://i.imgur.com/d4dRaRz.png",
    desc: "A.I. animation using two prompts. I animated the zoom attribute, while changing the prompt weights over time. Made with VQGAN+CLIP on Google Colab.",
    gridSize: "",
  },
  {
    name: "Ice Fractals",
    type: ["video", "audio"],
    src: "https://i.imgur.com/2uhc4v9.mp4",
    poster: "https://i.imgur.com/d4dRaRz.png",
    desc: "A.I. animation using two prompts. I animated the zoom attribute, while changing the prompt weights over time. Made with VQGAN+CLIP on Google Colab.",
    gridSize: "",
  },
  {
    name: "The Portal",
    type: ["images"],
    src: "https://i.imgur.com/aQgq262.jpg",
    desc: "Procedural terrain with some experimental lighting.",
    gridSize: "tall",
  },

  {
    name: "The Marble",
    type: ["images"],
    src: "https://i.imgur.com/7aiLIUN.png",
    tags: ["3d blender sci-fi planets"],
    desc: "The inspiration for this planet was Pluto, using it's nice colors and textures as reference.",
    gridSize: "",
  },
  {
    name: "Opal",
    type: ["youtube", "videos", "audio"],
    src: "//www.youtube.com/embed/KsevmMGJ3Cw",
    desc: 'Track 2 from "Neizbruseni Kamenja" EP',
    gridSize: "",
  },
  {
    name: "Philharmony",
    type: ["images"],
    src: "https://i.imgur.com/QsjIPrd.jpg",
    tags: ["3d blender abstract graphic-design"],
    desc: "Philrhamony is a two-track project, they needed a cover that would match the mood of the songs.",
    gridSize: "",
  },
  {
    name: "Treeman",
    type: ["images"],
    src: "https://i.imgur.com/UfU3omC.png",
    desc: "A 3D sculpture of an old drawing of mine.",
    gridSize: "tall",
  },
  {
    name: "Smaragd",
    type: ["youtube", "videos", "audio"],
    src: "//www.youtube.com/embed/3UDbgvsJYYU",
    desc: 'Track 1 from "Neizbruseni Kamenja" EP',
    gridSize: "",
  },
  {
    name: "Artificial Moon",
    type: ["images"],
    src: "https://i.imgur.com/ajYdr31.png",
    desc: "One of my first tries at A.I. animation and sound design.",
    gridSize: "",
  },
  {
    name: "The Starsnatcher",
    type: ["images"],
    src: "https://i.imgur.com/fQcTjjk.png",
    tags: ["3d blender sci-fi planets"],
    desc: "A different approach to the same procedure as the Firestorm nebula.",
    gridSize: "tall wide",
  },

  {
    name: "Getaway House",
    type: ["images"],
    src: "https://i.imgur.com/MbxjbZ5.jpg",
    desc: "The terrain and sky are procedurally generated. The painterly look was achieved with Blender's optiX denoiser.",
    gridSize: "wide",
  },
  {
    name: "Maschine MK3",
    type: ["images"],
    src: "https://i.imgur.com/GmwFgIt.jpg",
    desc: "A 3D model of my Maschine MK3. Decided to put it in a little scene.",
    gridSize: "",
  },
  {
    name: "Zhad",
    type: ["youtube", "videos", "audio"],
    src: "//www.youtube.com/embed/1TlzEe03FDY",
    desc: 'Track 5 from "Neizbruseni Kamenja" EP',
    gridSize: "",
  },
  {
    name: "Press Play",
    type: ["images"],
    src: "https://i.imgur.com/esLCgXy.jpg",
    desc: "My first try to sculpt in Blender. I think it turned out great.",
    gridSize: "",
  },
  {
    name: "Ladybugs",
    type: ["videos", "audio"],
    src: "https://i.imgur.com/EbHBNyM.mp4",
    desc: "Ladybugs on flowers, morphing into spiders on skulls.",
    gridSize: "",
  },
  {
    name: "Opsidijan",
    type: ["youtube", "videos", "audio"],
    src: "//www.youtube.com/embed/mOA0kEdJ9zw",
    desc: 'Track 7 from "Neizbruseni Kamenja" EP',
    gridSize: "",
  },
  {
    name: "The Hidden Planet",
    type: ["images"],
    src: "https://i.imgur.com/51d36S4.jpg",
    desc: "Blender's fluid simulations were used for the nebula, the planet is procedurally shaded.",
    gridSize: "tall",
  },
  {
    name: "Microcubes",
    type: ["images"],
    src: "https://i.imgur.com/bAR6oFX.jpg",
    desc: "Procedurally created microstructures in Blender.",
    gridSize: "",
  },
  {
    name: "Firestorm Nebula",
    type: ["images"],
    src: "https://i.imgur.com/7d7njCC.png",
    tags: ["3d blender sci-fi planets"],
    desc: "My first try at procedurally creating a nebula.",
    gridSize: "wide",
  },
  {
    name: "Ametist",
    type: ["youtube", "videos", "audio"],
    src: "//www.youtube.com/embed/xEAxqil5-m0",
    desc: 'Track 4 from "Neizbruseni Kamenja" EP',
    gridSize: "",
  },
  {
    name: "Monkey See",
    type: ["videos", "audio"],
    src: "https://i.imgur.com/PGbEwMR.mp4",
    desc: "Inspired by the intro of Marvel's \"What If...\" series, I was trying to achieve a procedural shading based on the camera's position.",
    gridSize: "wide",
  },
  {
    name: "Chija Si",
    type: ["images"],
    src: "https://i.imgur.com/Lym8xmJ.png",
    desc: "Winning design for the CD and vinyl cover of LD Pistolero ft. DJ Goce - Chija si",
    gridSize: "",
  },
  {
    name: "Strange Galaxies",
    type: ["videos", "audio"],
    src: "https://i.imgur.com/l1IzFK2.mp4",
    desc: "One of my first tries at A.I. animation and sound design.",
    gridSize: "",
  },

  {
    name: "Beril",
    type: ["youtube", "videos", "audio"],
    src: "//www.youtube.com/embed/M1LgnRHupU8",
    desc: 'Track 3 from "Neizbruseni Kamenja" EP',
    gridSize: "",
  },

  {
    name: "Vrvot na Trkaloto",
    type: ["youtube", "videos"],
    src: "//www.youtube.com/embed/VF8CRfzoeGY",
    desc: `I made this looping animation for a track called "Vrvot na Trkaloto". I was given a concept art for the environment and two characters, which I recreated in Blender. The environment itself is 3D, so I made sure for some elements to dynamically react to certain frequencies of the song.
    The final look of the character differs a bit from the original concept, since they had to be optimized for animation. I made sure to give them both a distinct walking style. There are of course a couple of easter eggs and unique animated moments, such as the cross flipping over at 0:44.`,
    gridSize: "wide",
  },
];
