export const ArtworkData = [
  {
    name: "Earth 6",
    type: "photos",
    src: "gallery/earf.png",
    tags: ["3d blender sci-fi planets"],
    alt: "earf",
    desc: "One of my first procedural planet renders. I was going for an earth-like planet with it's own moon.",
    gridSize: "",
  },
  {
    name: "The Marble",
    type: "photos",
    src: "gallery/pluto.png",
    tags: ["3d blender sci-fi planets"],
    alt: "pluto",
    desc: "The inspiration for this planet was Pluto, using it's nice colors and textures as reference.",
    gridSize: "wide tall",
  },
  {
    name: "The Last Voyage",
    type: "photos",
    src: "gallery/voyage.png",
    tags: ["3d blender concept-art landscapes"],
    alt: "last voyage",
    desc: "An attempt at creating a procedural scene. The ship and dock were added to .",
    gridSize: "wide",
  },
  {
    name: "Philharmony",
    type: "photos",
    src: "gallery/philharmony.png",
    tags: ["3d blender abstract graphic-design"],
    alt: "philharmony",
    desc: "Philrhamony is a two-track project, they needed a cover that would match the mood of the songs.",
    gridSize: "",
  },
  {
    name: "The Starsnatcher",
    type: "photos",
    src: "gallery/starsnatcher.png",
    tags: ["3d blender sci-fi planets"],
    alt: "earf",
    desc: "A different approach to the same procedure as the Firestorm nebula.",
    gridSize: "tall",
  },
  {
    name: "Firestorm Nebula",
    type: "photos",
    src: "gallery/firestorm.png",
    tags: ["3d blender sci-fi planets"],
    alt: "pluto",
    desc: "My first try at procedurally creating a nebula.",
    gridSize: "tall",
  },
  {
    name: "Treeman",
    type: "photos",
    src: "gallery/treeman.png",
    alt: "river",
    desc: "A 3D sculpture of an old drawing of mine.",
    gridSize: "tall",
  },
  {
    name: "Getaway House",
    type: "photos",
    src: "gallery/river.jpg",
    alt: "river",
    desc: "The terrain and sky are procedurally generated. The painterly look was achieved with Blender's optiX denoiser.",
    gridSize: "wide",
  },
];


